import Head from 'next/head'

export default function Home() {
    return (
        <>
            <Head>
                <title>Let's Communicate</title>
                <meta name="description" content="Generated by Let's Communicate" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <header>header</header>

            <main>
                <h1>Welcome to Let's Communicate</h1>
            </main>
            
            <footer>footer</footer>
        </>
    );
}